config/routes.rb
App::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  resources :playlists, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @songs = []
    if signed_in?
      current_user.playlists[current_user.current_playlist_id.to_i].songs.each do |song|
        if song.streamable?
          @songs += [{title: song.title, mp3: song.stream_url.to_s + "?client_id=7369d5fe3bc71c4163f76b36b04b1128", artwork_url: song.artwork_url}]
        end
      end
    else
      Song.all.each do |song|
        if song.streamable?
          @songs += [{title: song.title, mp3: song.stream_url.to_s + "?client_id=7369d5fe3bc71c4163f76b36b04b1128", artwork_url: song.artwork_url}]
        end
      end
    end
  end
  
  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

app/views/static_pages/home.html.erb
<%= stylesheet_link_tag "main" %>
<%= javascript_include_tag "jquery.jplayer.min" %>
<%= javascript_include_tag "jplayer.playlist.min" %>
<%= javascript_include_tag "jplayer.inspector.min" %>

<script>
$(document).ready(function(){
  var songs = <%= @songs.to_json.html_safe %>;
    
	playlist = new jPlayerPlaylist({
		jPlayer: "#jquery_jplayer_1",
		cssSelectorAncestor: "#jp_container_1"
	}, songs,
  {
    playlistOptions: {
        autoPlay: true,
        enableRemoveControls: true
    },
    play: function() { // The $.jPlayer.event.ended event
      updateAll(playlist.playlist[playlist.current]); // Repeat the media
    },
		swfPath: "/swf",
		supplied: "mp3",
		wmode: "window"
	});
  
	$("#jplayer_inspector_1").jPlayerInspector({jPlayer:$("#jquery_jplayer_1")});
  
  updateAll = function(song) {
    var currentTitle = song.title || 'Untitled';
    //var currentArtist = song.artist || 'Anonymous';
    var currentArt = song.artwork_url || '/no-art.png';
    $('#current-title').html(currentTitle);
    //$('#current-artist').html(currentArtist);
    $('#current-art')[0].src = currentArt;
    //$('title').html(songtitle + ' - ' + songartist);
  };
  
});
</script>

<div class="player">
  <div id="jquery_jplayer_1" class="jp-jplayer"></div>
		<div id="jp_container_1" class="jp-audio">
			<div class="jp-type-playlist">
        <div class="jp-gui jp-interface2">
          <div class="text-interface2">
            <img id="current-art" src=""></img>
            <div id="current-title"></div>
            <div id="current-artist"></div>
          </div>
        </div>
				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-previous" tabindex="1">previous</a></li>
						<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="javascript:;" class="jp-next" tabindex="1">next</a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>
						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
					<ul class="jp-toggles"></ul>
				</div>
				<div class="jp-playlist">
					<ul>
                
						<li></li>
                
					</ul>
				</div>
				<div class="jp-no-solution">
					<span>Update Required</span>
					To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
				</div>
			</div>
		</div>  
  </div>
</div>

<div class="sidebar">
  <% if signed_in? %>
  Welcome back, <%= current_user.name %>
    <%= link_to "Sign out", signout_path, method: "delete", class: "signout" %><br>
    
    <div id="user-playlists">
        <div class="given-playlists">
          <ul>
            <% (0..2).each do |num| %>
              <% if num == current_user.current_playlist_id %>
              <li id="current-playlist"><%= current_user.playlists[num].title %></li>
              <% else %>
                <li id="given"><%= current_user.playlists[num].title %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        
        <br>
        <h3>Make a new Playlist</h3><br>
        <% @playlist = Playlist.new %>
        <%= form_for @playlist, :remote => true, :url => { :controller => "playlists", :action => "create" } do |f| %>
          <%= f.text_field 'title', class: 'submittable' %>
        <% end %>
        
        
        <div class="more-playlist">
          <ul>
            <% current_user.playlists[3..current_user.playlists.length].each do |playlist| %>
              <% if playlist.id == current_user.current_playlist_id %>
                <li id="current-playlist"><%= playlist.title %></li>
              <% else %>
                <li id="regular-playlist"><%= playlist.title %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        
    </div>
    
  <% else %>
    <%= link_to "Sign in", signin_path, class: "signin" %>
    <%= link_to "Sign up", signup_path, class: "signup" %><br> 
  <% end %>
</div>

<div class="clear"></div>